name: test

jobs:
  test:
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1

      - name: Run Tests
        uses: deno test src/CollectionTests.ts
