name: test

on:
  push:
    branches:
      - "**" # matches every branch
jobs:
  test:
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1

      - name: Run Tests
        run: deno test src/CollectionTests.ts
